production:
  script:
    - deployer
    - export npm_config_registry=https://registry.npm.taobao.org
    - export npm_config_disturl=https://npm.taobao.org/dist
    - export npm_config_progress=true
    - npm install
    - ./node_modules/pm2/bin/pm2 restart index
  type: deploy
  only:
    - master

cache:
  untracked: true
  paths:
    - node_modules/
    - public/upload/
